# Netlify configuration file

# 1. Build Settings
# Specifies the build command, publish directory, and functions directory.
[build]
  command = "npm run build"
  publish = "build"
  functions = "netlify/functions"

# 2. Production Context
# These settings apply only to production deploys.
[context.production]
  # You can set production-specific environment variables here if needed.
  [context.production.environment]
    NODE_VERSION = "18"
    GENERATE_SOURCEMAP = "false"

  # 3. Netlify Asset Optimization
  # Enables built-in, high-performance asset optimization.
  # This can potentially replace your custom `scripts/optimize-images.js` script.
  [context.production.processing]
    skip_processing = false
  [context.production.processing.css]
    bundle = true
    minify = true
  [context.production.processing.js]
    minify = true
  [context.production.processing.images]
    optimize = true # Enables Netlify's built-in image optimization.
  [context.production.processing.html]
    pretty_urls = true

# 4. Caching Strategy
[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/_next/static/*" # If using Next.js (good for general purpose in case of future changes)
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/assets/*" # Specific for your project's assets
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/public/*" # Specific for your project's public directory
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.(js|css|png|jpg|jpeg|gif|svg|woff|woff2|eot|ttf|otf)"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*"
  [headers.values]
    Cache-Control = "public, max-age=2592000" # 1 month for other assets

[[headers]]
  for = "/index.html"
  [headers.values]
    Cache-Control = "no-cache, no-store, must-revalidate"
    Pragma = "no-cache"
    Expires = "0"
