# Netlify configuration file

# 1. Build Settings
# Specifies the build command, publish directory, and functions directory.
[build]
  command = "npm run build"
  publish = "build"
  functions = "netlify/functions"

# 2. Production Context
# These settings apply only to production deploys.
[context.production]
  # You can set production-specific environment variables here if needed.
  [context.production.environment]
    NODE_VERSION = "18"
    GENERATE_SOURCEMAP = "false"

  # 3. Netlify Asset Optimization
  # Enables built-in, high-performance asset optimization.
  # This can replace your custom `optimize:images` script.
  [context.production.processing]
    skip_processing = false
  [context.production.processing.css]
    bundle = true
    minify = true
  [context.production.processing.js]
    minify = true
  [context.production.processing.images]
    compress = true # Alias for optimize = true
  [context.production.processing.html]
    pretty_urls = true

# 4. SPA Redirect Rule
# Essential for client-side routers like React Router.
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# 5. Security & Caching Headers
[[headers]]
  for = "/static/*"
  [headers.values]
    # Cache static assets for a year.
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    # A basic Content-Security-Policy. This should be customized for your app.
    Content-Security-Policy = "default-src 'self' https://*.firebaseio.com https://*.googleapis.com; script-src 'self' 'unsafe-inline'; style-src 'self' 'unsafe-inline'; img-src 'self' data:; connect-src 'self' wss://*.firebaseio.com https://*.googleapis.com;"