# Netlify configuration file

# 1. Build Settings
# Specifies the build command, publish directory, and functions directory.
[build]
  command = "npm run build"
  publish = "build"
  functions = "netlify/functions"

# 2. Production Context
# These settings apply only to production deploys.
[context.production]
  # You can set production-specific environment variables here if needed.
  [context.production.environment]
    NODE_VERSION = "18"
    GENERATE_SOURCEMAP = "false"

  # 3. Netlify Asset Optimization
  # Enables built-in, high-performance asset optimization.
  # This can replace your custom `optimize:images` script.
  [context.production.processing]
    skip_processing = false
  [context.production.processing.css]
    bundle = true
    minify = true
  [context.production.processing.js]
    minify = true
  [context.production.processing.images]
    compress = true # Alias for optimize = true
  [context.production.processing.html]
    pretty_urls = true

# 4. SPA Redirect Rule
# Essential for client-side routers like React Router.
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# 5. API Redirects for Netlify Functions
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

# 6. Security & Caching Headers
[[headers]]
  for = "/static/*"
  [headers.values]
    # Cache static assets for a year.
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/assets/*"
  [headers.values]
    # Cache assets for 1 month
    Cache-Control = "public, max-age=2678400"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    # Updated Content-Security-Policy to allow invisible Firebase authentication
    Content-Security-Policy = "default-src 'self' https://*.firebaseio.com https://*.googleapis.com https://www.google.com https://www.gstatic.com; script-src 'self' 'unsafe-inline' https://*.firebaseio.com https://*.googleapis.com https://www.google.com https://www.gstatic.com https://apis.google.com; style-src 'self' 'unsafe-inline' https://cdnjs.cloudflare.com https://fonts.googleapis.com; img-src 'self' data: https://*.googleapis.com; connect-src 'self' wss://*.firebaseio.com https://*.googleapis.com https://www.google.com; frame-src 'self' https://*.firebaseio.com https://*.googleapis.com https://www.google.com;"
