# ==============================
# 🌐 Netlify Configuration File
# ==============================

# 1️⃣ BUILD SETTINGS
[build]
  command = "npm run build"
  publish = "build"
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "18"
  NODE_ENV = "production"
  GENERATE_SOURCEMAP = "false"

# 2️⃣ ASSET OPTIMIZATION
[build.processing]
  skip_processing = false

[build.processing.css]
  bundle = true
  minify = true

[build.processing.js]
  bundle = true
  minify = true

[build.processing.images]
  compress = true

# 3️⃣ CACHING STRATEGY
[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/public/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.(js|css|png|jpg|jpeg|gif|svg|woff|woff2|eot|ttf|otf)"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# 4️⃣ REDIRECTS
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

# Single Page App (SPA) redirect rule
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# 5️⃣ SECURITY & CSP HEADERS (✅ Updated for Razorpay)
[[headers]]
  for = "/*"
  [headers.values]
    # Security
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "no-referrer"
    # 🔐 CSP UPDATED — added https://checkout.razorpay.com
    Content-Security-Policy = "default-src 'self' https://*.firebaseio.com https://*.googleapis.com https://www.google.com https://www.gstatic.com; script-src 'self' 'unsafe-inline' 'unsafe-eval' https://*.firebaseio.com https://*.googleapis.com https://www.google.com https://www.gstatic.com https://checkout.razorpay.com; style-src 'self' 'unsafe-inline' https://cdnjs.cloudflare.com https://fonts.googleapis.com; font-src 'self' https://fonts.gstatic.com; img-src 'self' data: https://*.googleapis.com https://www.google.com https://www.gstatic.com; connect-src 'self' wss://*.firebaseio.com https://*.googleapis.com https://www.google.com https://api.emailjs.com https://script.google.com https://checkout.razorpay.com https://api.razorpay.com; frame-src 'self' https://www.google.com https://*.firebaseapp.com https://*.firebaseio.com https://checkout.razorpay.com; object-src 'none';"
    Cache-Control = "public, max-age=0, must-revalidate"

# 6️⃣ LONG CACHE FOR STATIC FILES
[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# 7️⃣ ALTERNATE GLOBAL CSP (optional duplicate safeguard)
[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = "script-src 'self' 'unsafe-inline' 'unsafe-eval' https://*.firebaseio.com https://*.googleapis.com https://www.google.com https://www.gstatic.com https://checkout.razorpay.com;"
    Referrer-Policy = "strict-origin-when-cross-origin"
