# Netlify configuration file

# 1. Build Settings
# Specifies the build command, publish directory, and functions directory.
[build]
  command = "npm run build"
  publish = "build"
  functions = "netlify/functions"

# Production environment settings
[build.environment]
  NODE_VERSION = "18"
  NODE_ENV = "production"
  # Disable source maps for smaller production builds
  GENERATE_SOURCEMAP = "false"

# Netlify's automatic asset optimization
[build.processing]
  skip_processing = false
[build.processing.css]
  bundle = true
  minify = true
[build.processing.js]
  bundle = true
  minify = true
[build.processing.images]
  compress = true

# 4. Caching Strategy
[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"



[[headers]]
  for = "/assets/*" # Specific for your project's assets
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/public/*" # Specific for your project's public directory
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.(js|css|png|jpg|jpeg|gif|svg|woff|woff2|eot|ttf|otf)"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Redirects for API calls to Netlify functions
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

# The following redirect is intended for single-page applications (SPAs).
# It ensures that any request that doesn't match a pre-existing file
# is redirected to the main index.html file.
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Caching and Security Headers
[[headers]]
  # Apply these headers to all pages
  for = "/*"
  [headers.values]
    # Prevent clickjacking
    X-Frame-Options = "DENY"
    # Prevent MIME-sniffing
    X-Content-Type-Options = "nosniff"
    # Control referrer information
    Referrer-Policy = "no-referrer"
    # Content Security Policy (CSP)
    # This is a stricter version of your existing CSP.
    # It allows resources from your site, Firebase, Google for reCAPTCHA, and EmailJS.
    Content-Security-Policy = "default-src 'self' https://*.firebaseio.com https://www.googleapis.com; script-src 'self' https://www.google.com https://www.gstatic.com https://script.google.com; style-src 'self' 'unsafe-inline'; img-src 'self' data:; connect-src 'self' wss://*.firebaseio.com https://*.googleapis.com https://api.emailjs.com https://script.google.com; frame-src 'self' https://www.google.com https://*.firebaseapp.com;"
    # Do not cache HTML files to ensure users get the latest version
    Cache-Control = "public, max-age=0, must-revalidate"

[[headers]]
  # Cache fingerprinted assets for one year
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
