# Netlify configuration file

# 1. Build Settings
[build]
  command = "npm run build:netlify"
  publish = "build"
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "18"
  NODE_ENV = "production"

# 2. Asset Processing
[build.processing]
  skip_processing = false

[build.processing.css]
  bundle = true
  minify = true

[build.processing.js]
  bundle = true
  minify = true

[build.processing.images]
  compress = true
  quality = 80

[build.processing.html]
  pretty_urls = true

# 3. Redirects and Headers
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "no-referrer"
    Content-Security-Policy = "default-src 'self' https://*.firebaseio.com https://www.googleapis.com; script-src 'self' https://www.google.com https://www.gstatic.com https://script.google.com https://apis.google.com; style-src 'self' 'unsafe-inline' https://cdnjs.cloudflare.com https://fonts.googleapis.com; font-src 'self' https://fonts.gstatic.com; img-src 'self' data:; connect-src 'self' wss://*.firebaseio.com https://*.googleapis.com https://api.emailjs.com https://script.google.com https://www.google.com; frame-src 'self' https://www.google.com https://*.firebaseapp.com;"
    Cache-Control = "public, max-age=0, must-revalidate"

[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/manifest.json"
  [headers.values]
    Cache-Control = "public, max-age=86400"

[[headers]]
  for = "/logo*.png"
  [headers.values]
    Cache-Control = "public, max-age=2592000"
